version: 2.1

commands:
  cmd-trufflehog-scan:
    parameters:
      disable_entropy:
        default: true
        description: Should we disable truffleHog's entropy detection?
        type: boolean
      max_history:
        default: "1"
        description: How far back to scan in git revisions
        type: string
      regexp_rules:
        default: ""
        description: Override default regexp rules with this file.
        type: string
      allowlist_file:
        default: ".circleci/trufflehog_config/allowlist.json"
        description: Add items to this file to allow you to override specific findings.
        type: string
      repo_path:
        default: .
        description: Scan alternate local or remote repo
        type: string
      current_branch:
        default: ${CIRCLE_BRANCH}
        description: Git branch to use
        type: string
    steps:
      - run:
          command: >
            trufflehog --regex --json \
                       --branch << parameters.current_branch >> \
                       <<# parameters.allowlist_file >> --allow << parameters.allowlist_file >> <</ parameters.allowlist_file >> \
                       <<# parameters.max_history >> --max_depth=<< parameters.max_history >> <</ parameters.max_history>> \
                       <<# parameters.disable_entropy >> --entropy=False <</ parameters.disable_entropy >> \
                       <<# parameters.regexp_rules >> --rules=<< parameters.regexp_rules >> <</ parameters.regexp_rules >> \
                       << parameters.repo_path >> \
                       | jq '{"reason":.reason,"path": .path}'
          name: Scan using truffleHog

jobs:
  run-trufflehog-scan:
    docker:
      - image: cimg/python:3.14
    parameters:
      current_branch:
        default: ${CIRCLE_BRANCH}
        description: Git branch to use
        type: string
    steps:
      - checkout
      - run:
          name: Install truffleHog
          command: pip install truffleHog
      - cmd-trufflehog-scan:
          current_branch: << parameters.current_branch >>

  run-sanity-check:
    docker:
      - image: hashicorp/terraform:1.14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apk add --update make
      - run:
          name: Format and validate
          command: make sanity-check

workflows:
  version: 2

  validate:
    jobs:
      - run-trufflehog-scan
      - run-sanity-check
