version: 2.1

jobs:
  run-sanity-check:
    docker:
      - image: hashicorp/terraform:1.14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apk add --update make
      - run:
          name: Format and validate
          command: make sanity-check

workflows:
  version: 2

  validate:
    jobs:
      - run-sanity-check
